### ISSUE TITLE
Error on Pocketmine 1.6

### ISSUE THREAD

**Issue by adendrag** [PocketMine/SimpleAuth#88]
Server thread/WARNING RuntimeException: "Illegal offset type" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 42

and

Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'SimpleAuth v1.7.1': Illegal offset type on SimpleAuth\EventListener

**Comment by HotFireyDeath** [comment]
Use SimpleAuthHelper http://forums.pocketmine.net/plugins/simpleauthhelper.1112/

It should fix this error.

**Comment by adendrag** [comment]
Still getting these errors:

Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46

Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': Illegal offset type in unset on SimpleAuth\EventListener

**Comment by HotFireyDeath** [comment]
Which API are you using? I used API 1.13.0 with SimpleAuthHelper plugin besides it. Helper should've been able to catch these errors.

**Comment by adendrag** [comment]
Same 1.13.0:
PocketMine-MP version 1.6dev-30 "[REDACTED]" (API 1.13.0)

**Comment by HotFireyDeath** [comment]
Okay. Yeah, it's SimpleAuth's errors. SimpleAuthHelper catches another error when logging in.
This error you specified happens when disconnecting?
SimpleAuth hasn't yet been optimized for API 0.13+, so I would recommend you to wait until a new update arrives, this issue should be left here.

**Comment by adendrag** [comment]
Yup, thanks.

**Comment by meulie** [comment]
I don't want to sound impatient, but is there an ETA for the API 0.13+ optimization of SimpleAuth?  :)
